// Auto-generated by generate.py — do not edit

export const DEFINITION = {
	Abbreviation: {
		tag: 'Abbreviation',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of an abbreviation.',
		parents: ['Abbreviations'],
		attributes: {
			sequence: ['descID', 'name'],
			details: {
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				name: { type: { builtin: 'normalizedString' }, required: true },
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Abbreviations: {
		tag: 'Abbreviations',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of abbreviations added by this namespace. Is cumulative to those defined in namespaces this one needs (may not redefine "included" ones.).',
		parents: ['NS', 'ServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Abbreviation'],
			details: {
				Abbreviation: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'Abbreviation', minOccurs: 1 }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueAbbreviation',
				selector: [{ steps: [{ kind: 'name', value: 'Abbreviation' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	AbstractLNClass: {
		tag: 'AbstractLNClass',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of an abstract logical node.',
		parents: ['LNClasses'],
		attributes: {
			sequence: ['base', 'deprecated', 'descID', 'informative', 'name', 'titleID'],
			details: {
				base: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: ['DataObject'],
			details: {
				DataObject: {},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'DataObject' }],
				},
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueDataObjectAbstractLNClass',
				selector: [{ steps: [{ kind: 'name', value: 'DataObject' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	ApplicableServiceNS: {
		tag: 'ApplicableServiceNS',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Root element of a file holding the allowed usages of ServiceNS-es.',
		parents: [],
		attributes: {
			sequence: ['date', 'version'],
			details: {
				date: { type: { builtin: 'dateTime' }, required: true },
				version: {
					type: { builtin: 'unsignedInt' },
					required: true,
					facets: { minInclusive: 0, maxInclusive: 4294967295 },
				},
			},
		},
		children: {
			sequence: ['Copyright', 'ServiceNsUsage'],
			details: {
				Copyright: { maxOccurs: 1 },
				ServiceNsUsage: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'Copyright', maxOccurs: 1 }],
				},
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'ServiceNsUsage', minOccurs: 1 }],
				},
			],
		},
	},
	ApplicableServices: {
		tag: 'ApplicableServices',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['FunctionalConstraint'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Service', 'DataSetMemberOf'],
			details: {
				Service: {},
				DataSetMemberOf: {},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{ kind: 'element', name: 'Service' },
				{ kind: 'element', name: 'DataSetMemberOf' },
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueDataSetMemberOf',
				selector: [{ steps: [{ kind: 'name', value: 'DataSetMemberOf' }] }],
				fields: [{ target: { kind: 'attribute', value: 'cb', isAttribute: true } }],
			},
			{
				kind: 'unique',
				name: 'uniqueService',
				selector: [{ steps: [{ kind: 'name', value: 'Service' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	AppliesTo: {
		tag: 'AppliesTo',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'References to namespaces this ServiceNS can be used with.',
		parents: ['ServiceNsUsage'],
		attributes: {
			sequence: ['id', 'publicationStage', 'release', 'revision', 'version'],
			details: {
				id: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['\\x00-\\x7f+'] },
				},
				publicationStage: {
					type: { builtin: 'token' },
					default: 'IS',
					facets: { enumeration: ['WD', 'CD', 'CDV', 'DTS', 'DTR', 'FDIS', 'TS', 'TR', 'IS'] },
				},
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	BasicType: {
		tag: 'BasicType',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['BasicTypes'],
		attributes: {
			sequence: ['descID', 'name'],
			details: {
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				name: { type: { builtin: 'token' }, required: true, facets: { minLength: 1 } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	BasicTypes: {
		tag: 'BasicTypes',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of basic types added by this namespace. Is cumulative to those defined in namespaces this one DependsOn (may not redefine "included" ones). Note: shall only be used in practice by the 7-2 namespace.',
		parents: ['NS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['BasicType'],
			details: {
				BasicType: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'BasicType', minOccurs: 1 }],
		},
	},
	CDC: {
		tag: 'CDC',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of a common data class.',
		parents: ['CDCs'],
		attributes: {
			sequence: [
				'deprecated',
				'descID',
				'enumParameterized',
				'informative',
				'name',
				'statistics',
				'titleID',
				'typeKindParameterized',
				'variant',
			],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				enumParameterized: { type: { builtin: 'boolean' }, default: 'false' },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				statistics: { type: { builtin: 'boolean' }, default: 'false' },
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
				typeKindParameterized: { type: { builtin: 'boolean' }, default: 'false' },
				variant: { type: { builtin: 'token' } },
			},
			identityFields: ['name', 'variant'],
		},
		children: {
			sequence: ['SubDataObject', 'DataAttribute', 'ServiceParameter'],
			details: {
				SubDataObject: {},
				DataAttribute: { required: true, minOccurs: 1 },
				ServiceParameter: { maxOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{ kind: 'element', name: 'SubDataObject' },
				{ kind: 'element', name: 'DataAttribute', minOccurs: 1 },
				{ kind: 'element', name: 'ServiceParameter', maxOccurs: 1 },
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueCDCChild',
				selector: [{ steps: [{ kind: 'wildcard' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	CDCs: {
		tag: 'CDCs',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of CDCs added by this namespace. CDCs are not allowed to be extended by another namespace. Note: shall only be used in practice by the 7-3',
		parents: ['NS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['CDC'],
			details: {
				CDC: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueCDCChild',
							selector: [{ steps: [{ kind: 'wildcard' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'CDC' }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueCDC',
				selector: [{ steps: [{ kind: 'name', value: 'CDC' }] }],
				fields: [
					{ target: { kind: 'attribute', value: 'name', isAttribute: true } },
					{ target: { kind: 'attribute', value: 'variant', isAttribute: true } },
				],
			},
		],
	},
	Changes: {
		tag: 'Changes',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'The version/revision/release this namespace is based on, including the TISSUEs implemented in this release.',
		parents: ['NS', 'ServiceNS'],
		attributes: {
			sequence: ['changesID', 'date', 'release', 'revision', 'tissues', 'version'],
			details: {
				changesID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				date: { type: { builtin: 'date' } },
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				tissues: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	ConstructedAttribute: {
		tag: 'ConstructedAttribute',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of a constructed (structured) data attribute.',
		parents: ['ConstructedAttributes'],
		attributes: {
			sequence: [
				'deprecated',
				'descID',
				'informative',
				'name',
				'titleID',
				'typeKindParameterized',
				'xsi:type',
			],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
				typeKindParameterized: { default: 'false' },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['tServiceConstructedAttribute'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: ['SubDataAttribute'],
			details: {
				SubDataAttribute: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'SubDataAttribute', minOccurs: 1 }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueSubDataAttribute',
				selector: [{ steps: [{ kind: 'name', value: 'SubDataAttribute' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	ConstructedAttributes: {
		tag: 'ConstructedAttributes',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of Constructed Attributes added by this namespace. Constructed Attributes are not allowed to be extended by another namespace. Note: shall only be used in practice by the 7-3',
		parents: ['NS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['ConstructedAttribute'],
			details: {
				ConstructedAttribute: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueSubDataAttribute',
							selector: [{ steps: [{ kind: 'name', value: 'SubDataAttribute' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'ConstructedAttribute' }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueConstructedAttribute',
				selector: [{ steps: [{ kind: 'name', value: 'ConstructedAttribute' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	Copyright: {
		tag: 'Copyright',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'The copyright notice attached to the XML',
		parents: ['NS', 'ServiceNS', 'NSDoc', 'ApplicableServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Notice', 'License'],
			details: {
				Notice: { required: true, minOccurs: 1, maxOccurs: 1 },
				License: { required: true, minOccurs: 1, maxOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{ kind: 'element', name: 'Notice', minOccurs: 1, maxOccurs: 1 },
				{ kind: 'element', name: 'License', minOccurs: 1, maxOccurs: 1 },
			],
		},
	},
	DataAttribute: {
		tag: 'DataAttribute',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['CDC'],
		attributes: {
			sequence: [
				'dchg',
				'defaultValue',
				'deprecated',
				'descID',
				'dupd',
				'fc',
				'informative',
				'isArray',
				'maxIndexAttribute',
				'maxValue',
				'minIndex',
				'minValue',
				'name',
				'presCond',
				'presCondArgs',
				'presCondArgsID',
				'qchg',
				'sizeAttribute',
				'type',
				'typeKind',
			],
			details: {
				dchg: { type: { builtin: 'boolean' }, default: 'false' },
				defaultValue: { type: { builtin: 'normalizedString' } },
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				dupd: { type: { builtin: 'boolean' }, default: 'false' },
				fc: {
					type: { builtin: 'token' },
					required: true,
					facets: { pattern: ['[\\x00-\\x7f]+'], minLength: 1 },
				},
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				isArray: { type: { builtin: 'boolean' }, default: 'false' },
				maxIndexAttribute: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				maxValue: { type: { builtin: 'decimal' } },
				minIndex: {
					type: { builtin: 'unsignedInt' },
					default: '0',
					facets: { minInclusive: 0, maxInclusive: 4294967295 },
				},
				minValue: { type: { builtin: 'decimal' } },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				presCond: { type: { builtin: 'normalizedString' }, default: 'M' },
				presCondArgs: { type: { builtin: 'normalizedString' } },
				presCondArgsID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				qchg: { type: { builtin: 'boolean' }, default: 'false' },
				sizeAttribute: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				type: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				typeKind: {
					type: {
						union: [
							{ builtin: 'token', facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] } },
							{ builtin: 'token', facets: { enumeration: ['undefined'] } },
						],
					},
					default: 'BASIC',
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED', 'undefined'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	DataObject: {
		tag: 'DataObject',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Child Data Object of the logical node.',
		parents: ['AbstractLNClass', 'LNClass'],
		attributes: {
			sequence: [
				'deprecated',
				'descID',
				'dsPresCond',
				'dsPresCondArgs',
				'dsPresCondArgsID',
				'informative',
				'name',
				'presCond',
				'presCondArgs',
				'presCondArgsID',
				'transient',
				'type',
				'underlyingType',
				'underlyingTypeKind',
			],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				dsPresCond: { type: { builtin: 'normalizedString' }, default: 'M' },
				dsPresCondArgs: { type: { builtin: 'normalizedString' } },
				dsPresCondArgsID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
						maxLength: 12,
					},
				},
				presCond: { type: { builtin: 'normalizedString' }, default: 'M' },
				presCondArgs: { type: { builtin: 'normalizedString' } },
				presCondArgsID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				transient: { type: { builtin: 'boolean' }, default: 'false' },
				type: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				underlyingType: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				underlyingTypeKind: {
					type: { builtin: 'token' },
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	DataSetMemberOf: {
		tag: 'DataSetMemberOf',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'An attribute of this FC can be member of a dataset for a control block type indicated by attribute cb if and only if this element is present.',
		parents: ['ApplicableServices'],
		attributes: {
			sequence: ['cb'],
			details: {
				cb: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { enumeration: ['RCB', 'LCB', 'GoCB', 'SVCB'] },
				},
			},
			identityFields: ['cb'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	DependsOn: {
		tag: 'DependsOn',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'The namespace identification this namespace depends on (and whose definitions are imported into this one).',
		parents: ['NS'],
		attributes: {
			sequence: ['id', 'publicationStage', 'release', 'revision', 'version'],
			details: {
				id: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['\\x00-\\x7f+'] },
				},
				publicationStage: {
					type: { builtin: 'token' },
					default: 'IS',
					facets: { enumeration: ['WD', 'CD', 'CDV', 'DTS', 'DTR', 'FDIS', 'TS', 'TR', 'IS'] },
				},
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	Doc: {
		tag: 'Doc',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of documentation identifiers and corresponding documentation strings in the corresponding language.',
		parents: ['NSDoc'],
		attributes: {
			sequence: ['id'],
			details: {
				id: { type: { builtin: 'normalizedString' }, required: true, facets: { minLength: 1 } },
			},
			identityFields: ['id'],
		},
		children: {
			sequence: [],
			any: true,
			details: {},
		},
		contentModel: {
			kind: 'sequence',
			particles: [
				{ kind: 'any', namespace: ['##any'], processContents: 'lax', minOccurs: 1, maxOccurs: 1 },
			],
		},
		textContent: {},
	},
	Enumeration: {
		tag: 'Enumeration',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of an enumeration.',
		parents: ['Enumerations'],
		attributes: {
			sequence: ['deprecated', 'descID', 'informative', 'inheritedFrom', 'name', 'titleID'],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				inheritedFrom: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: ['Literal'],
			details: {
				Literal: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'Literal', minOccurs: 1 }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueLiteralName',
				selector: [{ steps: [{ kind: 'name', value: 'Literal' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
			{
				kind: 'unique',
				name: 'uniqueLiteralVal',
				selector: [{ steps: [{ kind: 'name', value: 'Literal' }] }],
				fields: [{ target: { kind: 'attribute', value: 'literalVal', isAttribute: true } }],
			},
		],
	},
	Enumerations: {
		tag: 'Enumerations',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of Enumerations added by this namespace. Is cumulative to those defined in namespaces this one DependsOn (may not redefine "included" ones).',
		parents: ['NS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['Enumeration'],
			details: {
				Enumeration: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueLiteralName',
							selector: [{ steps: [{ kind: 'name', value: 'Literal' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
						{
							kind: 'unique',
							name: 'uniqueLiteralVal',
							selector: [{ steps: [{ kind: 'name', value: 'Literal' }] }],
							fields: [{ target: { kind: 'attribute', value: 'literalVal', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'Enumeration' }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueEnumeration',
				selector: [{ steps: [{ kind: 'name', value: 'Enumeration' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	FunctionalConstraint: {
		tag: 'FunctionalConstraint',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of a Functional Constraint.',
		parents: ['FunctionalConstraints'],
		attributes: {
			sequence: ['abbreviation', 'descID', 'titleID'],
			details: {
				abbreviation: {
					type: { builtin: 'token' },
					required: true,
					facets: { pattern: ['[\\x00-\\x7f]+'], minLength: 1 },
				},
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				titleID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
			},
			identityFields: ['abbreviation'],
		},
		children: {
			sequence: ['ApplicableServices'],
			details: {
				ApplicableServices: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueDataSetMemberOf',
							selector: [{ steps: [{ kind: 'name', value: 'DataSetMemberOf' }] }],
							fields: [{ target: { kind: 'attribute', value: 'cb', isAttribute: true } }],
						},
						{
							kind: 'unique',
							name: 'uniqueService',
							selector: [{ steps: [{ kind: 'name', value: 'Service' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'ApplicableServices', maxOccurs: 1 }],
		},
	},
	FunctionalConstraints: {
		tag: 'FunctionalConstraints',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of Functional Constraints added by this namespace. Is cumulative to those defined in namespaces this one DependsOn (may not redefine "included" ones).',
		parents: ['NS', 'ServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['FunctionalConstraint'],
			details: {
				FunctionalConstraint: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'FunctionalConstraint', minOccurs: 1 }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueFunctionalConstraint',
				selector: [{ steps: [{ kind: 'name', value: 'FunctionalConstraint' }] }],
				fields: [{ target: { kind: 'attribute', value: 'abbreviation', isAttribute: true } }],
			},
		],
	},
	LNClass: {
		tag: 'LNClass',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of a (non-abstract) logical node.',
		parents: ['LNClasses'],
		attributes: {
			sequence: [
				'base',
				'canHaveLOG',
				'deprecated',
				'descID',
				'informative',
				'isExtension',
				'name',
				'titleID',
			],
			details: {
				base: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				canHaveLOG: { type: { builtin: 'boolean' }, default: 'false' },
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				isExtension: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: { pattern: ['LLN0', '[A-Z]{4}', '[A-Za-z_:][-.:0-9A-Z_a-z]*'] },
				},
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: ['DataObject'],
			details: {
				DataObject: {},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'DataObject' }],
				},
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueDataObject',
				selector: [{ steps: [{ kind: 'name', value: 'DataObject' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	LNClasses: {
		tag: 'LNClasses',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of LNClasses added by this namespace. Is cumulative to those defined in namespaces this one DependsOn (may not redefine "included" ones).',
		parents: ['NS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['AbstractLNClass', 'LNClass'],
			details: {
				AbstractLNClass: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueDataObjectAbstractLNClass',
							selector: [{ steps: [{ kind: 'name', value: 'DataObject' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				LNClass: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueDataObject',
							selector: [{ steps: [{ kind: 'name', value: 'DataObject' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{ kind: 'element', name: 'AbstractLNClass' },
				{ kind: 'element', name: 'LNClass' },
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueAbstractLNClass',
				selector: [{ steps: [{ kind: 'name', value: 'AbstractLNClass' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
			{
				kind: 'unique',
				name: 'uniqueLNClass',
				selector: [{ steps: [{ kind: 'name', value: 'LNClass' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	License: {
		tag: 'License',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'The license definition.',
		parents: ['Copyright'],
		attributes: {
			sequence: ['kind', 'uri'],
			details: {
				kind: {
					type: { builtin: 'Name' },
					facets: {
						enumeration: ['Standard', 'Private', 'None'],
						pattern: ['[A-Za-z_:][-.:0-9A-Z_a-z]*'],
					},
				},
				uri: { type: { builtin: 'normalizedString' } },
			},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: {},
	},
	Literal: {
		tag: 'Literal',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['Enumeration'],
		attributes: {
			sequence: ['deprecated', 'descID', 'informative', 'literalVal', 'name'],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				literalVal: {
					type: { builtin: 'int' },
					required: true,
					facets: { minInclusive: -2147483648, maxInclusive: 2147483647 },
				},
				name: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['[\\x00-\\x7f\\x80-\\xff]*'], maxLength: 127 },
				},
			},
			identityFields: ['literalVal', 'name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	NS: {
		tag: 'NS',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Root element of a namespace definition (NSD) file.',
		parents: [],
		attributes: {
			sequence: [
				'descID',
				'id',
				'publicationStage',
				'release',
				'revision',
				'umlDate',
				'umlVersion',
				'version',
			],
			details: {
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				id: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['\\x00-\\x7f+'] },
				},
				publicationStage: {
					type: { builtin: 'token' },
					default: 'IS',
					facets: { enumeration: ['WD', 'CD', 'CDV', 'DTS', 'DTR', 'FDIS', 'TS', 'TR', 'IS'] },
				},
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				umlDate: { type: { builtin: 'dateTime' } },
				umlVersion: {
					type: { builtin: 'Name' },
					facets: { pattern: ['[A-Za-z_:][-.:0-9A-Z_a-z]*'], minLength: 1 },
				},
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: [
				'Copyright',
				'Changes',
				'DependsOn',
				'BasicTypes',
				'FunctionalConstraints',
				'PresenceConditions',
				'Abbreviations',
				'Enumerations',
				'ConstructedAttributes',
				'CDCs',
				'LNClasses',
			],
			details: {
				Copyright: { maxOccurs: 1 },
				Changes: { maxOccurs: 1 },
				DependsOn: { maxOccurs: 1 },
				BasicTypes: { maxOccurs: 1 },
				FunctionalConstraints: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueFunctionalConstraint',
							selector: [{ steps: [{ kind: 'name', value: 'FunctionalConstraint' }] }],
							fields: [{ target: { kind: 'attribute', value: 'abbreviation', isAttribute: true } }],
						},
					],
				},
				PresenceConditions: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniquePresenceCondition',
							selector: [{ steps: [{ kind: 'name', value: 'PresenceCondition' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				Abbreviations: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueAbbreviation',
							selector: [{ steps: [{ kind: 'name', value: 'Abbreviation' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				Enumerations: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueEnumeration',
							selector: [{ steps: [{ kind: 'name', value: 'Enumeration' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				ConstructedAttributes: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueConstructedAttribute',
							selector: [{ steps: [{ kind: 'name', value: 'ConstructedAttribute' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				CDCs: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueCDC',
							selector: [{ steps: [{ kind: 'name', value: 'CDC' }] }],
							fields: [
								{ target: { kind: 'attribute', value: 'name', isAttribute: true } },
								{ target: { kind: 'attribute', value: 'variant', isAttribute: true } },
							],
						},
					],
				},
				LNClasses: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueAbstractLNClass',
							selector: [{ steps: [{ kind: 'name', value: 'AbstractLNClass' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
						{
							kind: 'unique',
							name: 'uniqueLNClass',
							selector: [{ steps: [{ kind: 'name', value: 'LNClass' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'Copyright', maxOccurs: 1 }],
				},
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [
						{ kind: 'element', name: 'Changes', maxOccurs: 1 },
						{ kind: 'element', name: 'DependsOn', maxOccurs: 1 },
						{ kind: 'element', name: 'BasicTypes', maxOccurs: 1 },
						{ kind: 'element', name: 'FunctionalConstraints', maxOccurs: 1 },
						{ kind: 'element', name: 'PresenceConditions', maxOccurs: 1 },
						{ kind: 'element', name: 'Abbreviations', maxOccurs: 1 },
						{ kind: 'element', name: 'Enumerations', maxOccurs: 1 },
						{ kind: 'element', name: 'ConstructedAttributes', maxOccurs: 1 },
						{ kind: 'element', name: 'CDCs', maxOccurs: 1 },
						{ kind: 'element', name: 'LNClasses', maxOccurs: 1 },
					],
				},
			],
		},
	},
	NSDoc: {
		tag: 'NSDoc',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'Root element of a file holding the documentation strings of an NSD file (NSDOC).',
		parents: [],
		attributes: {
			sequence: [
				'id',
				'lang',
				'publicationStage',
				'release',
				'revision',
				'umlDate',
				'umlVersion',
				'version',
			],
			details: {
				id: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['\\x00-\\x7f+'] },
				},
				lang: {
					type: { builtin: 'language' },
					required: true,
					facets: { pattern: ['[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*'] },
				},
				publicationStage: {
					type: { builtin: 'token' },
					default: 'IS',
					facets: { enumeration: ['WD', 'CD', 'CDV', 'DTS', 'DTR', 'FDIS', 'TS', 'TR', 'IS'] },
				},
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				umlDate: { type: { builtin: 'dateTime' } },
				umlVersion: {
					type: { builtin: 'Name' },
					facets: { pattern: ['[A-Za-z_:][-.:0-9A-Z_a-z]*'], minLength: 1 },
				},
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: ['Copyright', 'Doc'],
			details: {
				Copyright: { maxOccurs: 1 },
				Doc: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'Copyright', maxOccurs: 1 }],
				},
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'Doc', minOccurs: 1 }],
				},
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueDocID',
				selector: [{ steps: [{ kind: 'name', value: 'Doc' }] }],
				fields: [{ target: { kind: 'attribute', value: 'id', isAttribute: true } }],
			},
		],
	},
	Notice: {
		tag: 'Notice',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'The textual copyright notice.',
		parents: ['Copyright'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: [],
			details: {},
		},
		textContent: {},
	},
	PresenceCondition: {
		tag: 'PresenceCondition',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Definition of a presence condition.',
		parents: ['PresenceConditions'],
		attributes: {
			sequence: ['argument', 'descID', 'name', 'titleID'],
			details: {
				argument: { type: { builtin: 'normalizedString' } },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				name: { type: { builtin: 'normalizedString' }, required: true },
				titleID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	PresenceConditions: {
		tag: 'PresenceConditions',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of presence conditions added by this namespace. Is cumulative to those defined in namespaces this one DependsOn (may not redefine "included" ones.).',
		parents: ['NS', 'ServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['PresenceCondition'],
			details: {
				PresenceCondition: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'PresenceCondition', minOccurs: 1 }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniquePresenceCondition',
				selector: [{ steps: [{ kind: 'name', value: 'PresenceCondition' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	Service: {
		tag: 'Service',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'If present, indicates that the service with given name applies to attributes with the specified FC (otherwise it may not be used).',
		parents: ['ApplicableServices'],
		attributes: {
			sequence: ['name'],
			details: {
				name: {
					type: { builtin: 'token' },
					required: true,
					facets: {
						enumeration: [
							'Associate',
							'Abort',
							'Release',
							'GetServerDirectory',
							'GetLogicalDeviceDirectory',
							'GetAllDataValues',
							'GetDataValues',
							'SetDataValues',
							'GetDataDirectory',
							'GetDataDefinition',
							'GetDataSetValues',
							'SetDataSetValues',
							'CreateDataSet',
							'DeleteDataSet',
							'GetDataSetDirectory',
							'SelectActiveSG',
							'SelectEditSG',
							'SetEditSGValue',
							'ConfirmEditSGValues',
							'GetEditSGValue',
							'GetSGCBValues',
							'Report',
							'GetBRCBValues',
							'SetBRCBValues',
							'GetURCBValues',
							'SetURCBValues',
							'GetLCBValues',
							'SetLCBValues',
							'QueryLogByTime',
							'QueryLogAfter',
							'GetLogStatusValues',
							'SendGOOSEMessage',
							'GetGoCBValues',
							'SetGoCBValues',
							'GetGoReference',
							'GetGOOSEElementNumber',
							'SendMSVMessage',
							'GetMSVCBValues',
							'SetMSVCBValues',
							'SendUSVMessage',
							'GetUSVCBValues',
							'SetUSVCBValues',
							'Select',
							'SelectWithValue',
							'Cancel',
							'Operate',
							'CommandTermination',
							'TimeActivatedOperate',
							'GetFile',
							'SetFile',
							'DeleteFile',
							'GetFileAttributeValues',
							'TimeSynchronization',
							'InternalChange',
							'GetLogicalNodeDirectory',
							'GetMsvReference',
							'GetMSVElementNumber',
							'GetUsvReference',
							'GetUSVElementNumber',
						],
					},
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	ServiceCDC: {
		tag: 'ServiceCDC',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'CDC extensions for control in this service namespace.',
		parents: ['ServiceCDCs'],
		attributes: {
			sequence: ['cdc', 'variant'],
			details: {
				cdc: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				variant: { type: { builtin: 'token' } },
			},
			identityFields: ['cdc', 'variant'],
		},
		children: {
			sequence: ['ServiceDataAttribute'],
			details: {
				ServiceDataAttribute: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'ServiceDataAttribute', minOccurs: 1 }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueServiceCDCChild',
				selector: [{ steps: [{ kind: 'name', value: 'ServiceDataAttribute' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	ServiceCDCs: {
		tag: 'ServiceCDCs',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of service CDCs added by this namespace. Is cumulative to those defined in namespaces this one needs (may not redefine "included" ones.).',
		parents: ['ServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['ServiceCDC'],
			details: {
				ServiceCDC: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueServiceCDCChild',
							selector: [{ steps: [{ kind: 'name', value: 'ServiceDataAttribute' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'ServiceCDC' }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueServiceCDC',
				selector: [{ steps: [{ kind: 'name', value: 'ServiceCDC' }] }],
				fields: [
					{ target: { kind: 'attribute', value: 'cdc', isAttribute: true } },
					{ target: { kind: 'attribute', value: 'variant', isAttribute: true } },
				],
			},
		],
	},
	ServiceConstructedAttribute: {
		tag: 'ServiceConstructedAttribute',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'Realization of Part 7-2 abstract types or constructed attributes needed for control services. Note: in SCL instance files, the ProtNs element shall be specified for these.',
		parents: ['ServiceConstructedAttributes'],
		attributes: {
			sequence: ['deprecated', 'descID', 'informative', 'name', 'titleID', 'typeKindParameterized'],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
				typeKindParameterized: { type: { builtin: 'boolean' }, default: 'false' },
			},
			identityFields: ['name'],
		},
		children: {
			sequence: ['SubDataAttribute'],
			details: {
				SubDataAttribute: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'SubDataAttribute', minOccurs: 1 }],
				},
			],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueSubDataAttribute_Service',
				selector: [{ steps: [{ kind: 'name', value: 'SubDataAttribute' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	ServiceConstructedAttributes: {
		tag: 'ServiceConstructedAttributes',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of service constructed attributes added by this namespace. Is cumulative to those defined in namespaces this one needs (may not redefine "included" ones.).',
		parents: ['ServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['ServiceConstructedAttribute'],
			details: {
				ServiceConstructedAttribute: {
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueSubDataAttribute_Service',
							selector: [{ steps: [{ kind: 'name', value: 'SubDataAttribute' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'ServiceConstructedAttribute' }],
		},
		constraints: [
			{
				kind: 'unique',
				name: 'uniqueServiceConstructedAttribute',
				selector: [{ steps: [{ kind: 'name', value: 'ServiceConstructedAttribute' }] }],
				fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
			},
		],
	},
	ServiceDataAttribute: {
		tag: 'ServiceDataAttribute',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Data attribute to be used as service parameter.',
		parents: ['ServiceCDC'],
		attributes: {
			sequence: [
				'deprecated',
				'descID',
				'fc',
				'informative',
				'name',
				'presCond',
				'presCondArgs',
				'presCondArgsID',
				'type',
				'typeKind',
				'underlyingType',
				'underlyingTypeKind',
			],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				fc: {
					type: { builtin: 'token' },
					required: true,
					facets: { pattern: ['[\\x00-\\x7f]+'], minLength: 1 },
				},
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				presCond: { type: { builtin: 'normalizedString' }, default: 'M' },
				presCondArgs: { type: { builtin: 'normalizedString' } },
				presCondArgsID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				type: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				typeKind: {
					type: {
						union: [
							{ builtin: 'token', facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] } },
							{ builtin: 'token', facets: { enumeration: ['undefined'] } },
						],
					},
					default: 'BASIC',
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED', 'undefined'] },
				},
				underlyingType: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				underlyingTypeKind: {
					type: { builtin: 'token' },
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	ServiceNS: {
		tag: 'ServiceNS',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Root element of a service namespace definition (SNSD) file.',
		parents: [],
		attributes: {
			sequence: [
				'descID',
				'id',
				'publicationStage',
				'release',
				'revision',
				'umlDate',
				'umlVersion',
				'version',
			],
			details: {
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				id: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['\\x00-\\x7f+'] },
				},
				publicationStage: {
					type: { builtin: 'token' },
					default: 'IS',
					facets: { enumeration: ['WD', 'CD', 'CDV', 'DTS', 'DTR', 'FDIS', 'TS', 'TR', 'IS'] },
				},
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				umlDate: { type: { builtin: 'dateTime' } },
				umlVersion: {
					type: { builtin: 'Name' },
					facets: { pattern: ['[A-Za-z_:][-.:0-9A-Z_a-z]*'], minLength: 1 },
				},
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: [
				'Copyright',
				'Changes',
				'FunctionalConstraints',
				'PresenceConditions',
				'Abbreviations',
				'ServiceTypeRealizations',
				'ServiceConstructedAttributes',
				'ServiceCDCs',
			],
			details: {
				Copyright: { maxOccurs: 1 },
				Changes: { maxOccurs: 1 },
				FunctionalConstraints: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueFunctionalConstraint_Service',
							selector: [{ steps: [{ kind: 'name', value: 'FunctionalConstraint' }] }],
							fields: [{ target: { kind: 'attribute', value: 'abbreviation', isAttribute: true } }],
						},
					],
				},
				PresenceConditions: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniquePresenceCondition_Service',
							selector: [{ steps: [{ kind: 'name', value: 'PresenceCondition' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				Abbreviations: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueAbbreviation_Service',
							selector: [{ steps: [{ kind: 'name', value: 'Abbreviation' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				ServiceTypeRealizations: { maxOccurs: 1 },
				ServiceConstructedAttributes: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueServiceConstructedAttribute',
							selector: [{ steps: [{ kind: 'name', value: 'ServiceConstructedAttribute' }] }],
							fields: [{ target: { kind: 'attribute', value: 'name', isAttribute: true } }],
						},
					],
				},
				ServiceCDCs: {
					maxOccurs: 1,
					constraints: [
						{
							kind: 'unique',
							name: 'uniqueServiceCDC',
							selector: [{ steps: [{ kind: 'name', value: 'ServiceCDC' }] }],
							fields: [
								{ target: { kind: 'attribute', value: 'cdc', isAttribute: true } },
								{ target: { kind: 'attribute', value: 'variant', isAttribute: true } },
							],
						},
					],
				},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [{ kind: 'element', name: 'Copyright', maxOccurs: 1 }],
				},
				{
					kind: 'sequence',
					minOccurs: 1,
					maxOccurs: 1,
					particles: [
						{ kind: 'element', name: 'Changes', maxOccurs: 1 },
						{ kind: 'element', name: 'FunctionalConstraints', maxOccurs: 1 },
						{ kind: 'element', name: 'PresenceConditions', maxOccurs: 1 },
						{ kind: 'element', name: 'Abbreviations', maxOccurs: 1 },
						{ kind: 'element', name: 'ServiceTypeRealizations', maxOccurs: 1 },
						{ kind: 'element', name: 'ServiceConstructedAttributes', maxOccurs: 1 },
						{ kind: 'element', name: 'ServiceCDCs', maxOccurs: 1 },
					],
				},
			],
		},
	},
	ServiceNsUsage: {
		tag: 'ServiceNsUsage',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation: 'Specification of a ServiceNS and all NS it can be used for.',
		parents: ['ApplicableServiceNS'],
		attributes: {
			sequence: ['id', 'publicationStage', 'release', 'revision', 'version'],
			details: {
				id: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { pattern: ['\\x00-\\x7f+'] },
				},
				publicationStage: {
					type: { builtin: 'token' },
					default: 'IS',
					facets: { enumeration: ['WD', 'CD', 'CDV', 'DTS', 'DTR', 'FDIS', 'TS', 'TR', 'IS'] },
				},
				release: {
					type: { builtin: 'unsignedByte' },
					default: '1',
					facets: { minInclusive: 0, maxInclusive: 255, minExclusive: 0 },
				},
				revision: { type: { builtin: 'token' }, default: 'A', facets: { pattern: ['[A-Z]'] } },
				version: {
					type: { builtin: 'unsignedShort' },
					required: true,
					facets: { minInclusive: 2002, maxInclusive: 2099 },
				},
			},
		},
		children: {
			sequence: ['AppliesTo'],
			details: {
				AppliesTo: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'AppliesTo', minOccurs: 1 }],
		},
	},
	ServiceParameter: {
		tag: 'ServiceParameter',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['CDC'],
		attributes: {
			sequence: [
				'defaultValue',
				'deprecated',
				'descID',
				'informative',
				'maxValue',
				'minValue',
				'name',
				'type',
				'typeKind',
			],
			details: {
				defaultValue: { type: { builtin: 'normalizedString' } },
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				maxValue: { type: { builtin: 'decimal' } },
				minValue: { type: { builtin: 'decimal' } },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				type: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				typeKind: {
					type: {
						union: [
							{ builtin: 'token', facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] } },
							{ builtin: 'token', facets: { enumeration: ['undefined'] } },
						],
					},
					default: 'BASIC',
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED', 'undefined'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	ServiceTypeRealization: {
		tag: 'ServiceTypeRealization',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'Realization of an abstract type as constructed attribute in the service namespace.',
		parents: ['ServiceTypeRealizations'],
		attributes: {
			sequence: [
				'deprecated',
				'descID',
				'informative',
				'name',
				'titleID',
				'typeKindParameterized',
				'xsi:type',
			],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				titleID: {
					type: { builtin: 'normalizedString' },
					required: true,
					facets: { minLength: 1 },
				},
				typeKindParameterized: { default: 'false' },
				'xsi:type': {
					namespace: { prefix: 'xsi', uri: 'http://www.w3.org/2001/XMLSchema-instance' },
					facets: { enumeration: ['tServiceConstructedAttribute'] },
				},
			},
		},
		children: {
			sequence: ['SubDataAttribute'],
			details: {
				SubDataAttribute: { required: true, minOccurs: 1 },
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'SubDataAttribute', minOccurs: 1 }],
		},
	},
	ServiceTypeRealizations: {
		tag: 'ServiceTypeRealizations',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		documentation:
			'List of service type realization added by this namespace. Is cumulative to those defined in namespaces this one needs (may not redefine "included" ones.).',
		parents: ['ServiceNS'],
		attributes: {
			sequence: [],
			details: {},
		},
		children: {
			sequence: ['ServiceTypeRealization'],
			details: {
				ServiceTypeRealization: {},
			},
		},
		contentModel: {
			kind: 'sequence',
			minOccurs: 1,
			maxOccurs: 1,
			particles: [{ kind: 'element', name: 'ServiceTypeRealization' }],
		},
	},
	SubDataAttribute: {
		tag: 'SubDataAttribute',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['ConstructedAttribute', 'ServiceTypeRealization', 'ServiceConstructedAttribute'],
		attributes: {
			sequence: [
				'defaultValue',
				'deprecated',
				'descID',
				'informative',
				'isArray',
				'maxIndexAttribute',
				'maxValue',
				'minIndex',
				'minValue',
				'name',
				'presCond',
				'presCondArgs',
				'presCondArgsID',
				'sizeAttribute',
				'type',
				'typeKind',
			],
			details: {
				defaultValue: { type: { builtin: 'normalizedString' } },
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				isArray: { type: { builtin: 'boolean' }, default: 'false' },
				maxIndexAttribute: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				maxValue: { type: { builtin: 'decimal' } },
				minIndex: {
					type: { builtin: 'unsignedInt' },
					default: '0',
					facets: { minInclusive: 0, maxInclusive: 4294967295 },
				},
				minValue: { type: { builtin: 'decimal' } },
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				presCond: { type: { builtin: 'normalizedString' }, default: 'M' },
				presCondArgs: { type: { builtin: 'normalizedString' } },
				presCondArgsID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				sizeAttribute: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				type: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				typeKind: {
					type: {
						union: [
							{ builtin: 'token', facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] } },
							{ builtin: 'token', facets: { enumeration: ['undefined'] } },
						],
					},
					default: 'BASIC',
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED', 'undefined'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
	SubDataObject: {
		tag: 'SubDataObject',
		namespace: { prefix: '', uri: 'http://www.iec.ch/61850/2016/NSD' },
		parents: ['CDC'],
		attributes: {
			sequence: [
				'deprecated',
				'descID',
				'informative',
				'isArray',
				'maxIndexAttribute',
				'minIndex',
				'name',
				'presCond',
				'presCondArgs',
				'presCondArgsID',
				'sizeAttribute',
				'type',
				'underlyingType',
				'underlyingTypeKind',
			],
			details: {
				deprecated: { type: { builtin: 'boolean' }, default: 'false' },
				descID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				informative: { type: { builtin: 'boolean' }, default: 'false' },
				isArray: { type: { builtin: 'boolean' }, default: 'false' },
				maxIndexAttribute: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				minIndex: {
					type: { builtin: 'unsignedInt' },
					default: '0',
					facets: { minInclusive: 0, maxInclusive: 4294967295 },
				},
				name: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				presCond: { type: { builtin: 'normalizedString' }, default: 'M' },
				presCondArgs: { type: { builtin: 'normalizedString' } },
				presCondArgsID: { type: { builtin: 'normalizedString' }, facets: { minLength: 1 } },
				sizeAttribute: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				type: {
					type: { builtin: 'Name' },
					required: true,
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				underlyingType: {
					type: { builtin: 'Name' },
					facets: {
						pattern: ['[\\x00-\\x7f\\x80-\\xff]+', '[A-Za-z_:][-.:0-9A-Z_a-z]*'],
						minLength: 1,
					},
				},
				underlyingTypeKind: {
					type: { builtin: 'token' },
					facets: { enumeration: ['BASIC', 'ENUMERATED', 'CONSTRUCTED'] },
				},
			},
			identityFields: ['name'],
		},
		children: {
			sequence: [],
			details: {},
		},
	},
} as const
