// Auto-generated by generate.py — do not edit

import type { ELEMENT_NAMES, REQUIRED_ATTRIBUTES } from './constants.generated'

export type AvailableElement = (typeof ELEMENT_NAMES)[number]

export type AttributesAbbreviation = {
	descID?: string
	name: string
}

export type AttributesAbbreviations = {}

export type AttributesAbstractLNClass = {
	base?: string
	deprecated?: string
	descID?: string
	informative?: string
	name: string
	titleID: string
}

export type AttributesApplicableServiceNS = {
	date: string
	version: string
}

export type AttributesApplicableServices = {}

export type AttributesAppliesTo = {
	id: string
	publicationStage?:
		| 'WD'
		| 'CD'
		| 'CDV'
		| 'DTS'
		| 'DTR'
		| 'FDIS'
		| 'TS'
		| 'TR'
		| 'IS'
		| (string & {})
	release?: string
	revision?: string
	version: string
}

export type AttributesBasicType = {
	descID?: string
	name: string
}

export type AttributesBasicTypes = {}

export type AttributesCDC = {
	deprecated?: string
	descID?: string
	enumParameterized?: string
	informative?: string
	name: string
	statistics?: string
	titleID: string
	typeKindParameterized?: string
	variant?: string
}

export type AttributesCDCs = {}

export type AttributesChanges = {
	changesID?: string
	date?: string
	release?: string
	revision?: string
	tissues?: string
	version: string
}

export type AttributesConstructedAttribute = {
	deprecated?: string
	descID?: string
	informative?: string
	name: string
	titleID: string
	typeKindParameterized?: string
	'xsi:type'?: 'tServiceConstructedAttribute' | (string & {})
}

export type AttributesConstructedAttributes = {}

export type AttributesCopyright = {}

export type AttributesDataAttribute = {
	dchg?: string
	defaultValue?: string
	deprecated?: string
	descID?: string
	dupd?: string
	fc: string
	informative?: string
	isArray?: string
	maxIndexAttribute?: string
	maxValue?: string
	minIndex?: string
	minValue?: string
	name: string
	presCond?: string
	presCondArgs?: string
	presCondArgsID?: string
	qchg?: string
	sizeAttribute?: string
	type?: string
	typeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | 'undefined' | (string & {})
}

export type AttributesDataObject = {
	deprecated?: string
	descID?: string
	dsPresCond?: string
	dsPresCondArgs?: string
	dsPresCondArgsID?: string
	informative?: string
	name: string
	presCond?: string
	presCondArgs?: string
	presCondArgsID?: string
	transient?: string
	type: string
	underlyingType?: string
	underlyingTypeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | (string & {})
}

export type AttributesDataSetMemberOf = {
	cb: 'RCB' | 'LCB' | 'GoCB' | 'SVCB' | (string & {})
}

export type AttributesDependsOn = {
	id: string
	publicationStage?:
		| 'WD'
		| 'CD'
		| 'CDV'
		| 'DTS'
		| 'DTR'
		| 'FDIS'
		| 'TS'
		| 'TR'
		| 'IS'
		| (string & {})
	release?: string
	revision?: string
	version: string
}

export type AttributesDoc = {
	id: string
}

export type AttributesEnumeration = {
	deprecated?: string
	descID?: string
	informative?: string
	inheritedFrom?: string
	name: string
	titleID: string
}

export type AttributesEnumerations = {}

export type AttributesFunctionalConstraint = {
	abbreviation: string
	descID?: string
	titleID?: string
}

export type AttributesFunctionalConstraints = {}

export type AttributesLNClass = {
	base?: string
	canHaveLOG?: string
	deprecated?: string
	descID?: string
	informative?: string
	isExtension?: string
	name: string
	titleID: string
}

export type AttributesLNClasses = {}

export type AttributesLicense = {
	kind?: 'Standard' | 'Private' | 'None' | (string & {})
	uri?: string
}

export type AttributesLiteral = {
	deprecated?: string
	descID?: string
	informative?: string
	literalVal: string
	name: string
}

export type AttributesNS = {
	descID?: string
	id: string
	publicationStage?:
		| 'WD'
		| 'CD'
		| 'CDV'
		| 'DTS'
		| 'DTR'
		| 'FDIS'
		| 'TS'
		| 'TR'
		| 'IS'
		| (string & {})
	release?: string
	revision?: string
	umlDate?: string
	umlVersion?: string
	version: string
}

export type AttributesNSDoc = {
	id: string
	lang: string
	publicationStage?:
		| 'WD'
		| 'CD'
		| 'CDV'
		| 'DTS'
		| 'DTR'
		| 'FDIS'
		| 'TS'
		| 'TR'
		| 'IS'
		| (string & {})
	release?: string
	revision?: string
	umlDate?: string
	umlVersion?: string
	version: string
}

export type AttributesNotice = {}

export type AttributesPresenceCondition = {
	argument?: string
	descID?: string
	name: string
	titleID?: string
}

export type AttributesPresenceConditions = {}

export type AttributesService = {
	name:
		| 'Associate'
		| 'Abort'
		| 'Release'
		| 'GetServerDirectory'
		| 'GetLogicalDeviceDirectory'
		| 'GetAllDataValues'
		| 'GetDataValues'
		| 'SetDataValues'
		| 'GetDataDirectory'
		| 'GetDataDefinition'
		| 'GetDataSetValues'
		| 'SetDataSetValues'
		| 'CreateDataSet'
		| 'DeleteDataSet'
		| 'GetDataSetDirectory'
		| 'SelectActiveSG'
		| 'SelectEditSG'
		| 'SetEditSGValue'
		| 'ConfirmEditSGValues'
		| 'GetEditSGValue'
		| 'GetSGCBValues'
		| 'Report'
		| 'GetBRCBValues'
		| 'SetBRCBValues'
		| 'GetURCBValues'
		| 'SetURCBValues'
		| 'GetLCBValues'
		| 'SetLCBValues'
		| 'QueryLogByTime'
		| 'QueryLogAfter'
		| 'GetLogStatusValues'
		| 'SendGOOSEMessage'
		| 'GetGoCBValues'
		| 'SetGoCBValues'
		| 'GetGoReference'
		| 'GetGOOSEElementNumber'
		| 'SendMSVMessage'
		| 'GetMSVCBValues'
		| 'SetMSVCBValues'
		| 'SendUSVMessage'
		| 'GetUSVCBValues'
		| 'SetUSVCBValues'
		| 'Select'
		| 'SelectWithValue'
		| 'Cancel'
		| 'Operate'
		| 'CommandTermination'
		| 'TimeActivatedOperate'
		| 'GetFile'
		| 'SetFile'
		| 'DeleteFile'
		| 'GetFileAttributeValues'
		| 'TimeSynchronization'
		| 'InternalChange'
		| 'GetLogicalNodeDirectory'
		| 'GetMsvReference'
		| 'GetMSVElementNumber'
		| 'GetUsvReference'
		| 'GetUSVElementNumber'
		| (string & {})
}

export type AttributesServiceCDC = {
	cdc: string
	variant?: string
}

export type AttributesServiceCDCs = {}

export type AttributesServiceConstructedAttribute = {
	deprecated?: string
	descID?: string
	informative?: string
	name: string
	titleID: string
	typeKindParameterized?: string
}

export type AttributesServiceConstructedAttributes = {}

export type AttributesServiceDataAttribute = {
	deprecated?: string
	descID?: string
	fc: string
	informative?: string
	name: string
	presCond?: string
	presCondArgs?: string
	presCondArgsID?: string
	type?: string
	typeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | 'undefined' | (string & {})
	underlyingType?: string
	underlyingTypeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | (string & {})
}

export type AttributesServiceNS = {
	descID?: string
	id: string
	publicationStage?:
		| 'WD'
		| 'CD'
		| 'CDV'
		| 'DTS'
		| 'DTR'
		| 'FDIS'
		| 'TS'
		| 'TR'
		| 'IS'
		| (string & {})
	release?: string
	revision?: string
	umlDate?: string
	umlVersion?: string
	version: string
}

export type AttributesServiceNsUsage = {
	id: string
	publicationStage?:
		| 'WD'
		| 'CD'
		| 'CDV'
		| 'DTS'
		| 'DTR'
		| 'FDIS'
		| 'TS'
		| 'TR'
		| 'IS'
		| (string & {})
	release?: string
	revision?: string
	version: string
}

export type AttributesServiceParameter = {
	defaultValue?: string
	deprecated?: string
	descID?: string
	informative?: string
	maxValue?: string
	minValue?: string
	name: string
	type?: string
	typeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | 'undefined' | (string & {})
}

export type AttributesServiceTypeRealization = {
	deprecated?: string
	descID?: string
	informative?: string
	name: string
	titleID: string
	typeKindParameterized?: string
	'xsi:type'?: 'tServiceConstructedAttribute' | (string & {})
}

export type AttributesServiceTypeRealizations = {}

export type AttributesSubDataAttribute = {
	defaultValue?: string
	deprecated?: string
	descID?: string
	informative?: string
	isArray?: string
	maxIndexAttribute?: string
	maxValue?: string
	minIndex?: string
	minValue?: string
	name: string
	presCond?: string
	presCondArgs?: string
	presCondArgsID?: string
	sizeAttribute?: string
	type?: string
	typeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | 'undefined' | (string & {})
}

export type AttributesSubDataObject = {
	deprecated?: string
	descID?: string
	informative?: string
	isArray?: string
	maxIndexAttribute?: string
	minIndex?: string
	name: string
	presCond?: string
	presCondArgs?: string
	presCondArgsID?: string
	sizeAttribute?: string
	type: string
	underlyingType?: string
	underlyingTypeKind?: 'BASIC' | 'ENUMERATED' | 'CONSTRUCTED' | (string & {})
}

export type AttributesMap = {
	Abbreviation: AttributesAbbreviation
	Abbreviations: AttributesAbbreviations
	AbstractLNClass: AttributesAbstractLNClass
	ApplicableServiceNS: AttributesApplicableServiceNS
	ApplicableServices: AttributesApplicableServices
	AppliesTo: AttributesAppliesTo
	BasicType: AttributesBasicType
	BasicTypes: AttributesBasicTypes
	CDC: AttributesCDC
	CDCs: AttributesCDCs
	Changes: AttributesChanges
	ConstructedAttribute: AttributesConstructedAttribute
	ConstructedAttributes: AttributesConstructedAttributes
	Copyright: AttributesCopyright
	DataAttribute: AttributesDataAttribute
	DataObject: AttributesDataObject
	DataSetMemberOf: AttributesDataSetMemberOf
	DependsOn: AttributesDependsOn
	Doc: AttributesDoc
	Enumeration: AttributesEnumeration
	Enumerations: AttributesEnumerations
	FunctionalConstraint: AttributesFunctionalConstraint
	FunctionalConstraints: AttributesFunctionalConstraints
	LNClass: AttributesLNClass
	LNClasses: AttributesLNClasses
	License: AttributesLicense
	Literal: AttributesLiteral
	NS: AttributesNS
	NSDoc: AttributesNSDoc
	Notice: AttributesNotice
	PresenceCondition: AttributesPresenceCondition
	PresenceConditions: AttributesPresenceConditions
	Service: AttributesService
	ServiceCDC: AttributesServiceCDC
	ServiceCDCs: AttributesServiceCDCs
	ServiceConstructedAttribute: AttributesServiceConstructedAttribute
	ServiceConstructedAttributes: AttributesServiceConstructedAttributes
	ServiceDataAttribute: AttributesServiceDataAttribute
	ServiceNS: AttributesServiceNS
	ServiceNsUsage: AttributesServiceNsUsage
	ServiceParameter: AttributesServiceParameter
	ServiceTypeRealization: AttributesServiceTypeRealization
	ServiceTypeRealizations: AttributesServiceTypeRealizations
	SubDataAttribute: AttributesSubDataAttribute
	SubDataObject: AttributesSubDataObject
}

export type AttributesOf<T extends AvailableElement> = AttributesMap[T]

export type RequiredAttributeNames<T extends AvailableElement> =
	(typeof REQUIRED_ATTRIBUTES)[T][number]
export type OptionalAttributeNames<T extends AvailableElement> = Exclude<
	keyof AttributesOf<T>,
	RequiredAttributeNames<T>
>
